# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Oc-Dome' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'MJRefresh'                      #刷新类
  pod 'SDWebImage' #图片下载
  pod 'AFNetworking', '~> 3.1.0' #网络请求
  pod 'MJExtension' #json->模型
  # U-Share SDK UI模块（分享面板，建议添加）
  pod 'UMCShare/UI'
  # 集成微信(精简版0.2M)
  pod 'UMCShare/Social/ReducedWeChat'
  # 集成QQ/QZone/TIM(精简版0.5M)
  pod 'UMCShare/Social/ReducedQQ'
  pod 'Masonry'
  pod 'DTCoreText', '~> 1.6.21'
  pod 'WechatOpenSDK'     #微信sdk
  pod 'Alipay-SDK'       #支付宝sdk
  pod 'FMDB'
end
