# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Oc-Dome' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Oc-Dome

  target 'Oc-DomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Oc-DomeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
